export type SkillCategory = {
  id: string;
  title: string;
  caption: string;
  items: string[];
};

export const skills: SkillCategory[] = [
  {
    id: "ai-native",
    title: "AI-native practice",
    caption: "How I work: substrate, not tooling.",
    items: [
      "LLM-powered Interfaces",
      "Agentic Workflows",
      "AI-augmented Design Systems",
      "Anthropic Claude",
      "OpenAI",
      "Google Gemini",
      "Meta Llama",
      "Claude Code",
      "Cursor",
      "Windsurf",
      "GitHub Copilot",
      "MCP (Model Context Protocol)",
      "Prompt Engineering",
      "Retrieval-augmented Generation",
      "Evals & Guardrails",
    ],
  },
  {
    id: "genai-creative",
    title: "GenAI creative workflows",
    caption: "Image, video, and audio pipelines I build with.",
    items: [
      "Midjourney",
      "Adobe Firefly",
      "Stable Diffusion",
      "ComfyUI",
      "DALL·E",
      "Sora",
      "Runway",
      "Veo",
      "ElevenLabs",
      "Suno",
      "Asset Pipeline Automation",
      "Brand-conditioned Generation",
    ],
  },
  {
    id: "design",
    title: "Design",
    caption: "How I think about people, problems, and form.",
    items: [
      "Systems Design",
      "Design Systems",
      "Design Tokens",
      "Prototyping",
      "Information Architecture",
      "Interaction Design",
      "Motion",
      "Accessibility (WCAG 2.2)",
      "Typography",
      "Visual Design",
    ],
  },
  {
    id: "creative-tools",
    title: "Creative tools",
    caption: "Where the pixels and frames come from.",
    items: [
      "Figma",
      "Figma Variables & Tokens",
      "FigJam",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe After Effects",
      "Adobe Premiere Pro",
      "Adobe InDesign",
      "Adobe XD",
      "Adobe Firefly",
      "Framer",
      "Storybook",
    ],
  },
  {
    id: "engineering",
    title: "Engineering, front end",
    caption: "What I reach for to ship the surface.",
    items: [
      "TypeScript",
      "React",
      "Next.js",
      "Web Components",
      "Tailwind CSS",
      "CSS Architecture",
      "Storybook",
      "Vite",
      "Playwright",
      "Jest / Vitest",
      "Git",
    ],
  },
  {
    id: "fullstack",
    title: "Engineering, full stack",
    caption: "What I reach for behind the surface.",
    items: [
      "Node.js",
      "Go",
      "C#",
      "Python",
      "REST API Design",
      "GraphQL",
      "OpenAPI / Swagger",
      "SDK Authoring",
      "OAuth / OIDC",
      "PostgreSQL",
      "Background Jobs & Queues",
      "Telemetry & Live-site",
    ],
  },
  {
    id: "platform",
    title: "Platform",
    caption: "Where things run.",
    items: [
      "AWS",
      "Azure",
      "Google Cloud",
      "Pulumi (IaC)",
      "Vercel",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
    ],
  },
  {
    id: "practice",
    title: "Practice",
    caption: "How I work with others.",
    items: [
      "Research Strategy",
      "Cross-functional Leadership",
      "Agile / Scrum",
      "Workshop Facilitation",
      "Mentorship",
      "Product Strategy",
      "Design Critique",
      "Regression Testing Methodology",
    ],
  },
];
