import type { Metadata } from "next";
import fs from "node:fs";
import path from "node:path";
import { Download, Mail, Globe, Linkedin, Github, MapPin } from "lucide-react";

import { profile } from "@/content/profile";
import { experience, education } from "@/content/experience";
import { skills } from "@/content/skills";
import { PrintButton } from "./PrintButton";

const PDF_HREF = "/dylan-kilgore-resume.pdf";
// Check at build time whether the static PDF artifact exists. If it does, the
// page surfaces a Download PDF button alongside the browser print fallback.
// Generated by `npm run generate:resume` (Puppeteer script).
function pdfExists(): boolean {
  return fs.existsSync(
    path.join(process.cwd(), "public", "dylan-kilgore-resume.pdf"),
  );
}

export const metadata: Metadata = {
  title: "Résumé",
  description: profile.about.bio.slice(0, 160),
};

function fmt(s: string) {
  if (s === "present") return "Present";
  const [y, m] = s.split("-");
  if (!m) return y;
  const month = new Date(`${s}-01`).toLocaleString("en-US", { month: "short" });
  return `${month} ${y}`;
}

function range(from: string, to: string) {
  return `${fmt(from)} — ${fmt(to)}`;
}

export default function ResumePage() {
  const hasPdf = pdfExists();
  return (
    <article className="resume-doc mx-auto max-w-[820px] px-6 pt-28 pb-24 print:p-0 print:pt-0 print:max-w-none">
      {/* Web-only toolbar — hidden in print. */}
      <div className="mb-10 flex items-center justify-between gap-4 print:hidden">
        <p className="text-xs uppercase tracking-[0.22em] text-[var(--fg-muted)]">
          Résumé
        </p>
        <div className="flex flex-wrap items-center gap-2">
          {hasPdf && (
            <a
              href={PDF_HREF}
              download="Dylan-Kilgore-Resume.pdf"
              className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-elevated)] px-4 py-2 text-sm font-medium transition-colors hover:border-[var(--section-accent)] hover:text-[var(--section-accent)]"
            >
              <Download size={14} aria-hidden />
              Download PDF
            </a>
          )}
          <PrintButton />
        </div>
      </div>

      {/* Header */}
      <header className="border-b border-[var(--border)] pb-6 print:border-b print:border-black/30 print:pb-3">
        <h1 className="text-4xl font-bold leading-tight md:text-5xl print:text-[26pt]">
          {profile.name}
        </h1>
        <p className="mt-2 text-[var(--fg-muted)] print:mt-1 print:text-[10pt]">
          {profile.title}
        </p>
        <ul className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-[var(--fg-muted)] print:mt-2 print:gap-x-4 print:text-[8.5pt]">
          {profile.location && (
            <li className="inline-flex items-center gap-1.5">
              <MapPin size={13} aria-hidden className="print:hidden" />
              {profile.location}
            </li>
          )}
          <li className="inline-flex items-center gap-1.5">
            <Mail size={13} aria-hidden className="print:hidden" />
            <a
              href={`mailto:${profile.social.email}`}
              className="hover:text-[var(--fg)] print:text-current print:no-underline"
            >
              {profile.social.email}
            </a>
          </li>
          {profile.social.linkedin && (
            <li className="inline-flex items-center gap-1.5">
              <Linkedin size={13} aria-hidden className="print:hidden" />
              <a
                href={`https://linkedin.com/in/${profile.social.linkedin}`}
                className="hover:text-[var(--fg)] print:text-current print:no-underline"
              >
                linkedin.com/in/{profile.social.linkedin}
              </a>
            </li>
          )}
          {profile.social.github && (
            <li className="inline-flex items-center gap-1.5">
              <Github size={13} aria-hidden className="print:hidden" />
              <a
                href={`https://github.com/${profile.social.github}`}
                className="hover:text-[var(--fg)] print:text-current print:no-underline"
              >
                github.com/{profile.social.github}
              </a>
            </li>
          )}
          <li className="inline-flex items-center gap-1.5">
            <Globe size={13} aria-hidden className="print:hidden" />
            <a
              href={profile.meta.siteUrl}
              className="hover:text-[var(--fg)] print:text-current print:no-underline"
            >
              beneficialmedia.com
            </a>
          </li>
        </ul>
      </header>

      {/* Summary */}
      <section className="mt-8 print:mt-4">
        <SectionTitle>Summary</SectionTitle>
        <p className="text-[var(--fg)] leading-relaxed print:text-[10pt] print:leading-snug">
          {profile.about.bio}
        </p>
      </section>

      {/* Experience */}
      <section className="mt-10 print:mt-5">
        <SectionTitle>Experience</SectionTitle>
        <ol className="space-y-7 print:space-y-3">
          {experience.filter((e) => !e.timelineOnly).map((e, i) => (
            <li
              key={`${e.company}-${e.from}-${i}`}
              className="break-inside-avoid print:break-inside-avoid"
            >
              <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
                <h3 className="text-lg font-bold print:text-[11pt]">
                  {e.company}
                  <span className="font-normal text-[var(--fg-muted)] print:text-black/70">
                    {" "}
                    · {e.role}
                  </span>
                </h3>
                <p className="text-xs uppercase tracking-[0.18em] text-[var(--fg-muted)] print:text-[8.5pt] print:tracking-normal print:normal-case print:text-black/70">
                  {range(e.from, e.to)}
                  {e.location ? ` · ${e.location}` : ""}
                </p>
              </div>
              {e.bullets && e.bullets.length > 0 ? (
                <ul className="mt-2 list-disc space-y-1.5 pl-5 text-sm leading-relaxed print:mt-1 print:space-y-0.5 print:text-[9.5pt] print:leading-snug">
                  {e.bullets.map((b, j) => (
                    <li key={j}>{b}</li>
                  ))}
                </ul>
              ) : (
                <p className="mt-2 text-sm leading-relaxed print:mt-1 print:text-[9.5pt] print:leading-snug">
                  {e.summary}
                </p>
              )}
            </li>
          ))}
        </ol>
      </section>

      {/* Education */}
      <section className="mt-10 print:mt-5 print:break-inside-avoid">
        <SectionTitle>Education</SectionTitle>
        <ul className="space-y-3 print:space-y-1">
          {education.map((ed) => (
            <li
              key={`${ed.school}-${ed.from}`}
              className="flex flex-wrap items-baseline justify-between gap-x-3"
            >
              <p className="font-medium print:text-[10pt]">
                {ed.school}
                <span className="font-normal text-[var(--fg-muted)] print:text-black/70">
                  {" "}
                  · {ed.credential}
                </span>
              </p>
              <p className="text-xs uppercase tracking-[0.18em] text-[var(--fg-muted)] print:text-[8.5pt] print:tracking-normal print:normal-case print:text-black/70">
                {ed.from} — {ed.to}
              </p>
            </li>
          ))}
        </ul>
      </section>

      {/* Skills */}
      <section className="mt-10 print:mt-5 print:break-inside-avoid">
        <SectionTitle>Skills</SectionTitle>
        <dl className="grid grid-cols-1 gap-3 print:gap-1.5">
          {skills.map((cat) => (
            <div
              key={cat.id}
              className="grid grid-cols-[140px_1fr] gap-3 print:grid-cols-[110px_1fr] print:gap-2"
            >
              <dt className="text-sm font-semibold text-[var(--fg-muted)] print:text-[9pt] print:text-black/70">
                {cat.title}
              </dt>
              <dd className="text-sm leading-relaxed print:text-[9pt] print:leading-snug">
                {cat.items.join(" · ")}
              </dd>
            </div>
          ))}
        </dl>
      </section>
    </article>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-[var(--fg-muted)] print:mb-1.5 print:text-[8.5pt] print:tracking-[0.18em] print:text-black/60">
      {children}
    </h2>
  );
}
